### PR TITLE
Add support for Round screen boundaries

### PR DESCRIPTION
**Pull request by niedzielski**
- Detect line collisions with the viewable area of any circular or
  rectangular Pebble.
- Make everything static where possible.

Sorry for the large patch. Please give this a shot and let me know what you think. I only have a Pebble Time Round so I tested on it and a Basalt[0] emulator. If you disagree with the code, let me know and I'll make amendments or you can merge and patch it.

[0] https://developer.getpebble.com/faqs/

### CODE REVIEW

**Comment by echosa** [comment]
Thanks for this! I'll look it over carefully soon, hopefully later today. A quick glance, though, shows that you changed a lot of functions and variables to static. I don't understand why.

**Comment by niedzielski** [comment]
Hello! I did that so the compiler and linker would recognize what code and data were local to the file and what might be used by other code. For example, the main function is called by the system so it's not static. Another example would be a library project which might expose a handful of non-static functions as a client API and keep hidden many internal implementation details in static functions and data. Static helps avoid naming collision, improves encapsulation, and may improve memory and performance. However, it's a minor point for this program so I'm happy to drop the change.

**Comment by echosa** [comment]
So, static/non-static in C are similar to private/public methods, respectively, in OOP classes? I didn't know that. If that's the case, I'm completely fine with those changes. Encapsulation and limiting scope are wonderful things.

**Comment by niedzielski** [comment]
Similar, yes. The `static` keyword when used at file scope limits the visibility of the function or variable operand to the file. When used on a variable within a function, it preserves the variable state across invocations. This patch applies only the first usage :)

**Comment by echosa** [comment]
I'm merging this now and will pull it and test it in CloudPebble. If all goes well, I'll build and deploy it. :-)

**Comment by niedzielski** [comment]
:dancer::dancer::dancer:

**Comment by echosa** [comment]
@niedzielski Version 2.0 is now released and in the app store! (Make sure to checkout the "Version Information" screen...) :-D :+1:

**Comment by niedzielski** [comment]
Thanks so much, @echosa! I am very sorry but I have bad news that the app doesn't seem to work when downloaded through the store :-( I just checked out your latest master branch, built it, and it worked perfectly. I even factory reset my watch but the production app just hangs. Is there any way the pbw or whatever file is uploaded to the store got corrupted some how? Can you test it again locally? I was so happy to download the app and see the icon there and so sad to deliver this news! In case it helps, here's the file generated from my system by checking out Etchist master, cleaning the repo, typing `waf configure` and `pebble build`. Let me know if there's anything I can do to get this resolved!

[Etchist-2015-12-16-22-59-88ffd7a.zip](https://github.com/echosa/Etchist/files/64972/Etchist-2015-12-16-22-59-88ffd7a.zip)

**Comment by echosa** [comment]
I just deleted Etchist from my Pebble then reinstalled it from the store. It worked fine for m. Can you try again? Maybe your store download had issues. Alternatively, do you have another Pebble to try it on? Before I pull it from the store and try anything else, I want to be sure of the issue.

**Comment by niedzielski** [comment]
Hm, I just unpaired my watch and phone, factory reset the watch, uninstalled the Pebble Store app from my phone, went through setup, and installed Etchist. :fire:It worked!!!! :fire: Thank heavens! Sorry to raise the false alarm! I thought I had done everything but previously I had only cleared the app cache and left the Bluetooth connection remembered. I'm super happy it's working!! Thank you so much for letting me contribute to such a fun app!

**Comment by echosa** [comment]
That's great news! I'm very thankful for the work you did. :-) I have no idea when I would have gotten around to it myself. Enjoy the app on your Round! You made it possible!

**Pull request merged**
