### PR TITLE
Upgrade to Pebble SDK v3.7

### PR DESCRIPTION
**Pull request by niedzielski**
Merge in changes to the standard project template generated by
"pebble new-project".

### CODE REVIEW

**Comment by echosa** [comment]
Thanks for doing this! I've been a terrible maintainer of this project so far, due to being alternately busy and lazy. The changes seem simple enough (interesting change to two space indentation... CloudPebble made it four). I'm going to assume this is fine, and if everything goes awry, I can always roll it back. 

I'm not familiar with the SDK changes, so will I need to build, deploy, and release the app to the app store again? Please let me know.

In the meantime, I'm calling this :+1: and merging. Thanks, again!

**Comment by niedzielski** [comment]
:+1:

**Comment by echosa** [comment]
@niedzielski Do I need to rebuild and deploy to the app store again?

**Comment by niedzielski** [comment]
Yes, the app will run on all Pebbles now.

**Comment by echosa** [comment]
Does that include the Pebble Round? I tried it in the emulator, and Etchist doesn't work well on the round. The assumes the screen is square, and thus is is possible to draw (and lose the cursor) in the cutoff corners. I do not want Etchist to be available for the Round unless and until this issue is resolved.

**Comment by niedzielski** [comment]
Rats! That's the watch I was hoping to get Etchist for! It's not a perfect experience yet. You can exclude Round by removing the "chalk" platform from appinfo.targetPlatforms.

**Comment by echosa** [comment]
Sorry! I'll still keep this PR merged because that's one step closer. Hopefully, I can find some time to change the code to detect if the watch is a Round, and change the screen boundaries accordingly. Until then, I don't want to release this, because the user experience isn't very good when you lose the cursor off-screen.

**Comment by niedzielski** [comment]
I'll see if I can put in a patch for Round boundaries tonight. Stay tuned! :)

**Comment by echosa** [comment]
I'd be very excited to see that and try it out! ^_^

**Pull request merged**
